### Brand qo'shish
POST http://localhost:3000/brands
Authorization: 
Content-Type: application/json

{
  "name": "Pilesos"
}

### Brandlar listini olish
GET http://localhost:3000/brands

### Bitta brandni olish
GET http://localhost:3000/brands/:id

### Brandni tahrirlash
PATCH http://localhost:3000/brands/:id
Authorization: 
Content-Type: application/json

{
  "name": ""
}

### Brandni o'chirish
DELETE http://localhost:3000/brands/:id
Authorization: 