POST http://localhost:3000/brands
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg3NzEwMzczLCJleHAiOjE2ODc4ODMxNzN9.DDjJpab0AsjM2BvWJlXcZpB7_PSscHQ6H8slmPqmQeM
Content-Type: application/json

{
  "name": "Razer"
}



###
GET http://localhost:3000/brands


###
GET http://localhost:3000/brands/7


###
PATCH http://localhost:3000/brands/10
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg3NzEwMzczLCJleHAiOjE2ODc4ODMxNzN9.DDjJpab0AsjM2BvWJlXcZpB7_PSscHQ6H8slmPqmQeM
Content-Type: application/json

{
  "name": "Talasaped"
}


###
DELETE http://localhost:3000/brands/10
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg3NzEwMzczLCJleHAiOjE2ODc4ODMxNzN9.DDjJpab0AsjM2BvWJlXcZpB7_PSscHQ6H8slmPqmQeM