### Kategoriya qo'shish
POST http://localhost:3000/categories
Content-Type: application/json
Authorization: 

{
  "name": ""
}

### Kategoriyalar listini olish
GET http://localhost:3000/categories

### Bitta kategoriyani olish
GET http://localhost:3000/categories/:id

### Kategoriyani tahrirlash
PATCH http://localhost:3000/categories/:id
Content-Type: application/json
Authorization: 

{
  "name": ""
}

### Kategoriyani o'chirish
DELETE http://localhost:3000/categories/:id
Authorization: 
