### Model qo'shish
POST http://localhost:3000/models
Authorization: 
Content-Type: application/json

{
  "name": "",
  "brand_id": 
}

### Modellar listini olish
GET http://localhost:3000/models

### Bitta modelni olish
GET http://localhost:3000/models/:id

### Modelni tahrirlash
PATCH http://localhost:3000/models/:id
Authorization: 
Content-Type: application/json

{
  "name": "",
  "brand_id": 
}

### Modelni o'chirish
DELETE http://localhost:3000/models/:id
Authorization: 