POST http://localhost:3000/models
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg3NzEwMzczLCJleHAiOjE2ODc4ODMxNzN9.DDjJpab0AsjM2BvWJlXcZpB7_PSscHQ6H8slmPqmQeM
Content-Type: application/json

{
  "name": "Priton",
  "brand_id": 9
}


###
GET http://localhost:3000/models



###
GET http://localhost:3000/models/12


###
PATCH http://localhost:3000/models/12
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg3NzEwMzczLCJleHAiOjE2ODc4ODMxNzN9.DDjJpab0AsjM2BvWJlXcZpB7_PSscHQ6H8slmPqmQeM
Content-Type: application/json

{
  "name": "Triton",
  "brand_id": 3
}


###
DELETE http://localhost:3000/models/12
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg3NzEwMzczLCJleHAiOjE2ODc4ODMxNzN9.DDjJpab0AsjM2BvWJlXcZpB7_PSscHQ6H8slmPqmQeM