### Noutbuklar listini olish
GET http://localhost:3000/noutbooks

### Bitta noutbukni olish
GET http://localhost:3000/noutbooks/:id

### Noutbukni o'chirish
DELETE http://localhost:3000/noutbooks/:id
Authorization: 

### Noutbukni kategoriyaga bog'lash
POST http://localhost:3000/noutbooks/:id/categories/:category_id
Authorization: 

### Noutbukni o'chirish
DELETE http://localhost:3000/noutbooks/:id/categories/:category_id
Authorization: 