POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "sardorbek",
  "password": "12345678"
}




###
GET http://localhost:3000/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg3NjEwMzk3LCJleHAiOjE2ODc3ODMxOTd9.ttbFW0MpIc-Q_x5iAmwvDLiNHSDcmjiCKPvLT5sGNMY


###
GET http://localhost:3000/users/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg3NjEwMzk3LCJleHAiOjE2ODc3ODMxOTd9.ttbFW0MpIc-Q_x5iAmwvDLiNHSDcmjiCKPvLT5sGNMY





###
PATCH http://localhost:3000/users/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg3NjEwMzk3LCJleHAiOjE2ODc3ODMxOTd9.ttbFW0MpIc-Q_x5iAmwvDLiNHSDcmjiCKPvLT5sGNMY
Content-Type: application/json

{
  "first_name": "Sardor",
  "last_name": "Yuldashev",
  "username": "sardorbek",
  "password": "12345678"
}